-- Sadece bu INSERT'i çalıştırın (tablo zaten var)
insert into public.budget_items
  (sort_order, category, category_en,
   plan_2023_2024, actual_2023_2024,
   plan_2024_2025, actual_2024_2025,
   plan_2025_2026,
   expense_categories, description_tr, description_en)
values
  (1,  'KIRTASİYE VE YÖNETİM GİDERLERİ',         'ADMINISTRATIVE EXPENSES',                         12500,   14436,   19000,   12932,   18106,   ARRAY['Donanım / Malzeme','Banka Masrafları'],         'Planlanan tutarlar, bir önceki dönemin gerçekleşen tutarına %40 enflasyon oranı eklenerek belirlenmiştir.', 'The planned amounts were determined by adding a 40% inflation rate to the previous period''s actual amounts.'),
  (2,  'PERSONEL GİDERLERİ',                       'EMPLOYEE EXPENSES',                               250000,  239500,  360000,  366140,  637710,  ARRAY['Personel Maaşı'],                              'Çalışanın 10 aylık maliyeti, 45.000 TL maaş ve 18.771 TL SGK/damga vergisinden oluşmaktadır.',             'The employee''s 10-month cost consists of a 45,000 TL salary and 18,771 TL for SGK and stamp tax.'),
  (3,  'KIDEM TAZMİNATI FONU',                     'SEVERANCE PAY',                                   68000,   55000,   25000,   20003,   45000,   ARRAY['SGK'],                                         NULL, NULL),
  (4,  'BAKIM ONARIM VE TEMİZLİK GİDERLERİ',      'MAINTENANCE REPAIR AND CLEANING EXPENSES',        50000,   92876,   130000,  95994,   134392,  ARRAY['Genel Bakım','Boya / Tadilat'],                 '2025-2026 dönemi için %40 enflasyon oranı eklenmiştir.', NULL),
  (5,  'BAHÇE BAKIM GİDERLERİ',                    'GARDEN EXPENSES',                                 40000,   31333,   50000,   57420,   80390,   ARRAY['Bahçe / Tarım'],                               NULL, NULL),
  (6,  'HAVUZ KİMYASALLARI VE GİDERLERİ',         'POOL CHEMICALS AND EXPENSES',                     77500,   96958,   135000,  102600,  143640,  ARRAY['Havuz Bakımı'],                                NULL, NULL),
  (7,  'ELEKTRİK GİDERLERİ',                      'ELECTRIC EXPENSES',                               70000,   54000,   85000,   87675,   122745,  ARRAY['Elektrik'],                                    NULL, NULL),
  (8,  'DEMİRBAŞ MALZEME ALIMLARI',                'FIXED ASSET PURCHASES',                           15000,   9225,    15000,   0,       50000,   ARRAY['Donanım / Malzeme'],                           'Havuz pompası, dalgıç pompası ve çim biçme makinası; hasar tespiti sonrasında yenileme/onarım yapılacaktır.', 'Pool pump, submersible pump and lawnmower will be replaced or repaired after damage assessment.'),
  (9,  'HAVUZ KORKULUKLARI ONARIMI',               'POOL RAILING REPAIR',                             20000,   0,       0,       108000,  0,       ARRAY['Demir / Metal İşleri'],                        NULL, NULL),
  (10, 'ÇATI ONARIMI',                             'ROOF REPAIR',                                     10000,   45500,   20000,   76750,   0,       ARRAY['Genel Bakım'],                                 NULL, NULL),
  (11, 'DENGE DEPOSU SU KAÇAĞI ONARIMI',           'BALANCE TANK WATER LEAK REPAIR',                  45000,   118000,  0,       0,       0,       ARRAY['Kanalizasyon'],                                NULL, NULL),
  (12, 'E BLOK TEMEL DRENAJI TADİLATI',            'E BLOC WATER DRAINAGE CONSTRUCTION',              50000,   35000,   0,       0,       0,       ARRAY['Kanalizasyon'],                                NULL, NULL),
  (13, 'HAVUZ FİLTRESİ DEĞİŞİMİ',                 'POOL FILTER CHANGE',                              22500,   0,       25000,   0,       0,       ARRAY['Havuz Bakımı'],                                NULL, NULL),
  (14, 'ÖDENMEMİŞ SGK BORCU 4 AYLIK',             'UNPAID PREMIUM DEBT',                             NULL,    25600,   25600,   29302,   0,       ARRAY['SGK'],                                         NULL, NULL),
  (15, 'ÖNGÖRÜLMEYEN GİDERLER',                   'UNFORESEEN EXPENSES',                             NULL,    41000,   91000,   71500,   100100,  ARRAY['Diğer'],                                       'Demir aksam onarımı, drenaj ve bakım masrafları çıkarılarak belirlenmiştir.', 'Determined by subtracting ironwork, drainage and maintenance costs.'),
  (16, 'C-D BLOK DEMİR AKSAM ONARIMLARI',         'C-D BLOCK IRONWORK REPAIRS',                      0,       0,       0,       70000,   0,       ARRAY['Demir / Metal İşleri'],                        NULL, NULL),
  (17, 'C-D BLOK DRENAJ İŞİ',                     'C-D BLOCK DRAINAGE WORK',                         0,       0,       0,       260000,  0,       ARRAY['Kanalizasyon'],                                NULL, NULL),
  (18, 'A-B-E-F BLOK DEMİR AKSAM ONARIMLARI',     'A-B-E-F BLOCK IRONWORK REPAIRS',                  NULL,    NULL,    NULL,    0,       196000,  ARRAY['Demir / Metal İşleri'],                        'Geçen yıl 2 blok onarımı maliyeti ve %40 enflasyon esas alınarak hesaplanmıştır.', 'Estimated based on the cost of last year''s 2-block repair and 40% inflation rate.'),
  (19, 'ESKİ ÇALIŞAN PERSONELE İKİ MAAŞ YARDIM', 'ASSISTANCE OF TWO SALARIES TO FORMER EMPLOYEE',   NULL,    NULL,    NULL,    NULL,    50000,   ARRAY['Personel Maaşı'],                              NULL, NULL),
  (20, 'ÇOCUK PARKI TADİLATI',                    'CHILDREN''S PLAYGROUND RENOVATION',               NULL,    NULL,    NULL,    NULL,    50000,   ARRAY['Genel Bakım'],                                 'Mevcut ekipmanların bakım/onarımı ve güvenlik standartlarına uygun hale getirilmesi.', 'Maintenance and repair of existing equipment to meet safety standards.'),
  (21, 'HAVUZ AÇILIŞ MASRAF BÖLÜMÜ',              'SWIMMING POOL OPENING EXPENSE SECTION',           NULL,    NULL,    NULL,    NULL,    10000,   ARRAY['Diğer'],                                       'Havuz sezonu başında sosyal etkinlik bütçesi.', 'Social event budget for the beginning of the pool season.');
